#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --set-scaled --save debian-bspwm/bg.jpg &
nm-applet &
picom -f &
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
